### ISSUE TITLE
python3 gen_schema.py --net resnet18 --save_path ./schema/resnet18.json 报错

### ISSUE THREAD

**Issue by GeneralJing** [Sanster/pytorch-network-slimming#8]
Traceback (most recent call last):
  File "gen_schema.py", line 31, in <module>
    y = model.features(x)
  File "/home/xxx/anaconda3/envs/slim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ResNet' object has no attribute 'features'

**Comment by Sanster** [comment]
torchvision 的版本？

**Comment by Sanster** [comment]
调试用的代码忘记删了，已修复：https://github.com/Sanster/pytorch-network-slimming/commit/e3fd71d3d2d21b00acc03249cc83f15c7161a077
