### ISSUE TITLE
AssertionError: len(in_keep_idxes): 16, module.weight.shape[1]: 1

### ISSUE THREAD

**Issue by GeneralJing** [Sanster/pytorch-network-slimming#9]
Traceback (most recent call last):
  File "gen_schema.py", line 78, in <module>
    pruner.run(0.1) # j
  File "/home/xxx/zxz/pytorch-network-slimming/src/pns/pns.py", line 307, in run
    conv2d.prune(
  File "/home/xxx/zxz/pytorch-network-slimming/src/pns/pns.py", line 50, in prune
    self.in_channels_keep_idxes, self.out_channels_keep_idxes = prune_conv2d(
  File "/home/xxx/zxz/pytorch-network-slimming/src/pns/functional.py", line 75, in prune_conv2d
    assert (
AssertionError: len(in_keep_idxes): 16, module.weight.shape[1]: 1

生成schema的json文件时，模型应该是加载了训练好的权重吧，我可以正常生成json文件，但是传入的x的batchsize不能是1，是1会报错，我设置成8就可以了，但是在下面代码中进行prune操作时，崩了，如上。

**Comment by GeneralJing** [comment]
嗯 大佬git上留的邮箱常用吗？给你发邮件吧

**Comment by GeneralJing** [comment]
已发邮件

**Comment by GeneralJing** [comment]
batch size设置的地方大概知道原因了，大佬有时间帮忙看下剪枝报错那个问题。网络的结构在邮件里。

**Comment by Sanster** [comment]
有分组卷积，分组卷积不支持🥲
